modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "justhammers"
version = "${version}"
displayName = "Just Hammers"
authors = "ErrorMikey"
description = '''
Add hammers to the game that are able to mine in a 3x3, 3x3x3, 5x5x3 and finally a 5x5x5! They're pretty awesome.
'''
#logoFile = ""

[[dependencies.justhammers]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
