modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "justhammers"
version = "${version}"
displayName = "Just Hammers"
authors = "ErrorMikey"
description = '''
Just hammers!
'''
#logoFile = ""

[[dependencies.justhammers]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"
