modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "smashy"
version = "${version}"
displayName = "Hammers go Smash"
authors = "ErrorMikey"
description = '''
Smashy hammers!
'''
#logoFile = ""

[[dependencies.smashy]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smashy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smashy]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"
